### PR TITLE
151 hover over previews

### PR DESCRIPTION
**Pull request by olayway**
Closing #151

## Changes
- tooltip on hovering over anchor tags linking to concepts

## Notes
- at the moment the content displayed in a tooltip is extracted from the original md file, which is fetched from our repo, parsed, and the first paragraph is used,
  - (maybe) another option could be moving the steps related to extracting first file paragraph to a new github workflow -> could be triggered on 'push', i.e. every time any changes are made to content files, md file extracts would be generated and stored in JSON files in a separate folder. This could also involve checks to ensure that for every file a paragraph was successfully extracted (and perform other checks against it).
- at the moment tooltips are only shown for links pointing to concepts since it made the most  sense to me this way, but it can be changed easily,
- tooltips are not shown on the whole `/guide` page as it seems href link format is not consistent on this page (e.g. some have this form `../concepts/{file}`, but some have `/concepts/{file}` even though they point to files in the same folder). I'll have to investigate that and tweak the code.

### CODE REVIEW

**Review by khalilcodes — COMMENTED** [review]
I think rather than doing a fetch from `https://raw.github...`, the files are locally accessible through contentlayer. *For eg. we can do:* 

```javascript
import { allOtherPages } from "contentlayer/generated"

allOtherPages.map((page)=> {
        ...
        const md = page.body.raw
        const extract = documentExtract(md)
        ...
})
```

Excellent execution of code! 👏

**Comment by olayway** [comment]
Thank you @khalilcodes for reviewing this so quickly ! :clap: :smiley: 

As for importing pages from contentlayer: I agree it would be better to import content from `./contenlayer/generated` instead of fetching them from github, however, loading `AllOtherPages` object which holds all pages and filtering for the ones with specific `_raw.sourceFilePath` is not the most optimal approach either. Unless there is a way to configure contentlayer to expose (i.e. export) all pages individually as weel. This way we could dynamically import specific files needed for a given href (its tooltip) instead of the whole `AllOtherPages` object? Do you possibly you know how to do it?

**Comment by khalilcodes** [comment]
You are right about optimization though. Looking at the [contentlayer docs](https://www.contentlayer.dev/docs/sources/files/generated-data), I can see we can do something like this maybe:

```javascript
import { allDocuments } from "contentlayer/generated"

const docs = allDocuments.filter(doc => doc["_id"] === path)
```

Going over a bit more though as to what exports are available. Maybe `OtherPage` which is a type...

**Comment by olayway** [comment]
It seems to me there is no way to import a single page from contentlayer, but I went for filtering for it based on the path to keep it consistent with how we do it in other parts of the project. Plus it eliminates some of the bugs related to inconsistencies in href paths, so we are able to preview page content also on the `/guide` page atm :)

**Review by khalilcodes — APPROVED** [review]
This is nice!! and loads quick too. ⚡ 

Note: after merging we should update the 'Acceptance' for the related issue (maybe with screenshots) of what we have covered here. I think we missed doing this for previous issues too. 🤦‍♂️

**Pull request merged**
