### PR TITLE
[site/home]: Latest releases section from page frontmatter

### LINKED ISSUE #136: Latest Releases on homepage from frontmatter
Latest releases section on the homepage to display videos from pages in frontmatter 

## Acceptance:

* [x] Latest releases list based on frontmatter `featured: true` in *date order* with most recent first
* [x] Cards with following info:
     - title
     - description
     - image
     - link to webpage for that "post/note"

## Tasks:

* [x] Refactor latest releases section to display list of featured
* [x] Update pages (currently featured on homepage) with required frontmatter

## UPDATE:
**Since latest releases are basically featured blog posts / pages, it's not required to restructure frontmatter as stated below. Content should be the same.**

## Notes:
**Disregard. see update above**
Following are the **BLOCKERS** to be addressed

- title (page title and card title do not match ??)
- description (page description and card description are different ??)
- some pages may not need a youtube video on them (add separate boolean field to display on page ??)

Possible solution would be to convert the youtube field to a nested field in frontmatter with the above info. *see below for eg.*
```
// page frontmatter ...
---
title: ...
description: ...
youtube:
  - title: ...
  - link: ...
  - descritption: ...
  - image: ...
  - featured: true (on homepage)
  - page: false (display on this page ?)
---
```

### PR DESCRIPTION
**Pull request by khalilcodes**
## Displaying latest releases on homepage based on frontmatter in pages

Resolves #136 

Pages with frontmatter having title, description. etc.. and setting the field `featured: true` will show up in the latest releases section on the homepage.

This PR includes the following tasks:

* [x]  Display latest releases posts if `featured: true` in pages frontmatter
        - *in date order with most recent first*
* [x] Cards:
      - title, description, image (*from page*), linked to post
      - description has been limited (end with ...) *for better design aesthetics*
* [x] Pages modified with frontmatter to match as currently on site:
      - notes/pia-mancini-open-collective-dialogue.md
      - notes/post-state-technocracy.md
      - notes/collective-action-problems-and-climate-change.md

### Additional:

- General card layout with custom height background in place of the image *for general posts without image eg. title and description only*
- Link to youtube video in card for posts with youtube

## Notes: 

Above pages content (title and description) have been changed to match with current matter in latest releases section.

## Test:

The test.md has been updated with frontmatter. In development, see how latest releases section displays posts by changing the field `featured: true` with/without an image `image: ...`

### CODE REVIEW

**Comment by rufuspollock** [comment]
@khalilcodes this is great.

One question was i thought we might have more than 3 featured items e.g. we'd show all of the deep dives. Can we customize it to show all of the latest releases for now?

**Comment by rufuspollock** [comment]
@khalilcodes let's just have the grid - slider is poorish UX and more work i suspect ...

**Comment by rufuspollock** [comment]
@khalilcodes what happened with showing **all** the deep dives. I still don't see them on the front page and this is something that is really important IMO.

**Comment by khalilcodes** [comment]
@rufuspollock I have asked Eilidh as to which pages/topics relate to deep dives and will include them thereafter. If these are all the pages that are included within the notes folder then I think the frontpage will look a bit clustered esp on mobile. Maybe we can initially have 6 or 9 in grid and then have a show more / show less button to expand ?

**Comment by rufuspollock** [comment]
@khalilcodes it is definitely *not* all the notes in the notes folder - it is just the ones related to the deep dives and other major conversations. When did you ask @EilidhRoss1 about this? (I ask so we can improve processes a bit as this has now had back and forth for nearly 2 months 😉)

**Comment by khalilcodes** [comment]
@rufuspollock 

> When did you ask @EilidhRoss1 about this? ...

I just asked her yesterday, so no issues in process I believe. I do agree that this got buried in light of other tasks as we moved on. The related issue shouldn't have closed and I may have forgotten to update the acceptance there.

> For now can we just have a grid of 3x per row ...

This is done and I will open a PR in a bit for review.

**Pull request merged**
